/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaapplication10;

import javax.swing.JFrame;

/**
 *
 * @author Hoang
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton_StartGame = new javax.swing.JButton();
        jMenuBar_Main = new javax.swing.JMenuBar();
        jMenu_StartGame = new javax.swing.JMenu();
        jMenu_LevelDiff = new javax.swing.JMenu();
        jMenuItem_Level1 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenuItem12 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenu_Scores = new javax.swing.JMenu();
        jMenuItem_PersonalScore = new javax.swing.JMenuItem();
        jMenuItem_AllScores = new javax.swing.JMenuItem();
        jMenu_Help = new javax.swing.JMenu();
        jMenuIttem_Instruction = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 255));
        jLabel1.setText("Welcome to Space Invaders Game");

        jButton_StartGame.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton_StartGame.setForeground(new java.awt.Color(255, 0, 0));
        jButton_StartGame.setText("Quick Game");
        jButton_StartGame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_StartGameActionPerformed(evt);
            }
        });

        jMenu_StartGame.setText("Start Game");

        jMenu_LevelDiff.setText("Level of Difficulty");

        jMenuItem_Level1.setText("Level 1");
        jMenuItem_Level1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_Level1ActionPerformed(evt);
            }
        });
        jMenu_LevelDiff.add(jMenuItem_Level1);

        jMenuItem7.setText("Level 2");
        jMenu_LevelDiff.add(jMenuItem7);

        jMenuItem11.setText("Level 3");
        jMenu_LevelDiff.add(jMenuItem11);

        jMenuItem12.setText("Level 4");
        jMenu_LevelDiff.add(jMenuItem12);

        jMenuItem10.setText("Level 5");
        jMenu_LevelDiff.add(jMenuItem10);

        jMenu_StartGame.add(jMenu_LevelDiff);

        jMenuItem8.setText("Death Mode");
        jMenu_StartGame.add(jMenuItem8);

        jMenuItem9.setText("God Mode");
        jMenu_StartGame.add(jMenuItem9);

        jMenuBar_Main.add(jMenu_StartGame);

        jMenu_Scores.setText("View Scores");

        jMenuItem_PersonalScore.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem_PersonalScore.setText("Personal Achivements");
        jMenuItem_PersonalScore.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_PersonalScoreActionPerformed(evt);
            }
        });
        jMenu_Scores.add(jMenuItem_PersonalScore);

        jMenuItem_AllScores.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem_AllScores.setText("The board scores");
        jMenuItem_AllScores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_AllScoresActionPerformed(evt);
            }
        });
        jMenu_Scores.add(jMenuItem_AllScores);

        jMenuBar_Main.add(jMenu_Scores);

        jMenu_Help.setText("Help");

        jMenuIttem_Instruction.setText("Instruction");
        jMenuIttem_Instruction.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuIttem_InstructionActionPerformed(evt);
            }
        });
        jMenu_Help.add(jMenuIttem_Instruction);

        jMenuItem3.setText("About");
        jMenu_Help.add(jMenuItem3);

        jMenuBar_Main.add(jMenu_Help);

        setJMenuBar(jMenuBar_Main);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(151, 151, 151)
                        .addComponent(jButton_StartGame, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(51, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(jLabel1)
                .addGap(33, 33, 33)
                .addComponent(jButton_StartGame, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(69, Short.MAX_VALUE))
        );

        setBounds(0, 0, 483, 301);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuIttem_InstructionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuIttem_InstructionActionPerformed
        // TODO add your handling code here:
        HelpJFrame helpframe= new HelpJFrame();
        helpframe.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        helpframe.setVisible(true);
    }//GEN-LAST:event_jMenuIttem_InstructionActionPerformed

    private void jMenuItem_Level1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_Level1ActionPerformed
        // TODO add your handling code here:
        GameScene gScene = new GameScene(Window.DEFAULT_WIDTH,
                                         Window.DEFAULT_HEIGHT);
        gScene.revalidate();
        gScene.repaint();
        //window.addScene(gScene);
        Window window = new Window(Window.DEFAULT_WIDTH,
                                   Window.DEFAULT_HEIGHT, gScene);
    }//GEN-LAST:event_jMenuItem_Level1ActionPerformed

    private void jButton_StartGameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_StartGameActionPerformed
        // TODO add your handling code here:
        GameScene gScene = new GameScene(Window.DEFAULT_WIDTH,
                                         Window.DEFAULT_HEIGHT);
        gScene.revalidate();
        gScene.repaint();
        //window.addScene(gScene);
        Window window = new Window(Window.DEFAULT_WIDTH,
                                   Window.DEFAULT_HEIGHT, gScene);
    }//GEN-LAST:event_jButton_StartGameActionPerformed

    private void jMenuItem_PersonalScoreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_PersonalScoreActionPerformed
        // TODO add your handling code here:
        PersonalScores inscore= new PersonalScores();
        inscore.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        inscore.setVisible(true);
    }//GEN-LAST:event_jMenuItem_PersonalScoreActionPerformed

    private void jMenuItem_AllScoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_AllScoresActionPerformed
        // TODO add your handling code here:
        AllScoreJFrame allscore = new AllScoreJFrame();
        allscore.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        allscore.setVisible(true);
    }//GEN-LAST:event_jMenuItem_AllScoresActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_StartGame;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar_Main;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JMenuItem jMenuItem_AllScores;
    private javax.swing.JMenuItem jMenuItem_Level1;
    private javax.swing.JMenuItem jMenuItem_PersonalScore;
    private javax.swing.JMenuItem jMenuIttem_Instruction;
    private javax.swing.JMenu jMenu_Help;
    private javax.swing.JMenu jMenu_LevelDiff;
    private javax.swing.JMenu jMenu_Scores;
    private javax.swing.JMenu jMenu_StartGame;
    // End of variables declaration//GEN-END:variables
}
